### ISSUE TITLE
Readynas package removal does not work

### ISSUE THREAD

**Issue by DJFliX** [Mhynlo/readynas-docker-cli#2]
When attempting to uninstall the package the ReadyNAS frontend returns an error and fails to remove the package.

**Comment by Mhynlo** [comment]
Did you have any specific details regarding the error message that you are getting?
`journal -af` during the uninstall should help me out a bit.

There is another version that I am coming out that will be treating this package as more of a backend/middleware framework interface. When working on Portainer as an alternative app package made some design limitations in the UI app package.
Reason I mention this is that I am still working out some kinks regarding the uninstall.

**Comment by DJFliX** [comment]
Unfortunately the command yields the following:
```
root@ReadyNAS:~# journal -af
-bash: journal: command not found
```

I tried looking around in /var/log but I couldn't find output relevant to the uninstall process. But I'm also no sure where to look so it might be in there somewhere :/

**Comment by Mhynlo** [comment]
Sorry. I miss wrote the command. It's `journalctl -af` since most of the services are running in systemd.

**Comment by Mhynlo** [comment]
While I was debugging I was not able to see the error in the UI since the UI refreshes when I uninstall the app.
I did see an error to the `systemctl stop docker`, and that was the part that was failing during the uninstall process from what I have encountered. It looked like a common message with docker, so I added it to the safe list, and then I didn't see the error during the uninstall anymore.

That fix was in the newer build:
https://github.com/Mhynlo/readynas-docker-cli/releases/tag/17.03-1

**Comment by Mhynlo** [comment]
I found an issue in this area.
There is an issue where if fails to delete the btrfs subvolumes before removing the directory.

**Comment by Mhynlo** [comment]
I made a fix for removing the docker packages with this commit: 8acd097
I have built the package that would need to be installed before the uninstall will work properly:
https://github.com/Mhynlo/readynas-docker-cli/releases/tag/17.06.0-ml1

I also have the app check for the docker-ce debian package for updates instead of this meta package.

**Comment by DJFliX** [comment]
@Mhynlo YOU, sir, are AWESOME!
